services:
  loki:
    image: grafana/loki:${LOKI_VERSION}
    #build:
    #  context: ./loki
    #  args:
    #    - LOKI_VERSION=${LOKI_VERSION}
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_ROOT_URL: /
    depends_on:
      - ${LOKI_SERVICE}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: http://${LOKI_HOST}:${LOKI_PORT}/loki/api/v1/push
        labels: service

volumes:
  loki_data:
  grafana_data: