apiVersion: 1
datasources:
  - name: Mimir
    type: prometheus
    uid: mimir-ds
    url: http://mimir:8080/prometheus
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceId
          url: http://tempo:3200/api/traces/${traceId} # Optional: If integrating with Tempo
    readOnly: false
